version: '3.2'
services:
  unifi-freeradius-ldap:
    image: haor/freeradius-google-ldap:latest
    # uncomment this line for debug
    #command: freeradius -X
    env_file: env/freeradius.env
    build:
      dockerfile: Dockerfile
      context: .
    image: haor/freeradius-google-ldap:latest
    #command: -X
    env_file: env/freeradius.env
    volumes:
      - type: bind
        source: ./certs
        target: /certs
    network_mode: host
