services:
  unifi-freeradius-ldap:
    build: .
    image: ghcr.io/odit-services/freeradius-sldap
    # command: -X
    env_file: .env
    volumes:
      - type: bind
        source: ./certs
        target: /certs
    ports:
      - 1812:1812/tcp
      - 1812:1812/udp
      - 1813:1813
      - 18120:18120
      - 60785:60785
      - 43261:43261
